services:
  django-app:
    build: .
    container_name: maxicom_django
    ports:
      - "8080:8000"
    env_file: .env
  db:
    image: postgres:18
    container_name: maxicom_db
    depends_on:
      - django-app
    env_file: .env
    volumes:
      - "postgres_db:/var/lib/postgresql/18/docker"

volumes:
  postgres_db:
